name: Tests

on:
  pull_request:
  push:
    branches:
      - release-v*.*.*

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run developper workflow
        run:
          make dev
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint tests
        run:
          make lint
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run:
          make unit
  integration:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run:
          make integration
